name = "step_handler"
description = "Generate a Tasker step handler class with RSpec test"

[[parameters]]
name = "name"
description = "Handler name (e.g., ProcessPayment)"
required = true

[[parameters]]
name = "module_name"
description = "Module namespace for the handler"
required = false
default = "Handlers"

[[outputs]]
template = "handler.rb.tera"
filename = "{{ name | snake_case }}_handler.rb"

[[outputs]]
template = "handler_spec.rb.tera"
filename = "{{ name | snake_case }}_handler_spec.rb"
subdir = "spec"
